name: windows

on: 
    workflow_dispatch:
    schedule:
    # * is a special character in YAML so you have to quote this string
    # https://docs.github.com/cn/actions/reference/events-that-trigger-workflows#scheduled-events
      - cron:  '0 0 * * 5'

env:
  CONFIG: Release

jobs:
  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        algorithms: [vulkan]
    steps:
    - uses: actions/checkout@v2
    - uses: snickerbockers/submodules-init@v4
    - name: cache-vulkan
      id: cache-vulkan
      uses: actions/cache@v2.1.6
      with:
        path: "VulkanSDK"
        key: VulkanSDK-1.2.189.2-Installer
    - name: install-vulkan
      if: steps.cache-vulkan.outputs.cache-hit != 'true'
      run: |
        Invoke-WebRequest -Uri https://sdk.lunarg.com/sdk/download/1.2.189.2/windows/VulkanSDK-1.2.189.2-Installer.exe?Human=true -OutFile VulkanSDK-1.2.189.2-Installer.exe
        7z x -aoa ./VulkanSDK-1.2.189.2-Installer.exe -oVulkanSDK
        Remove-Item .\VulkanSDK\Demos, .\VulkanSDK\glslang, .\VulkanSDK\Samples, .\VulkanSDK\shaderc, .\VulkanSDK\spirv-tools, .\VulkanSDK\Third-Party, .\VulkanSDK\Tools, .\VulkanSDK\Tools32 -Recurse
    - name: build-x86
      working-directory: ${{github.workspace}}
      run: |
        cmake $env:GITHUB_WORKSPACE -T v142,host=x64 -A Win32 -B build-x86
        cmake --build build-x86 --config $env:CONFIG -j 2
    - name: build-x64
      working-directory: ${{github.workspace}}
      run: |
        cmake $env:GITHUB_WORKSPACE -B build-x64
        cmake --build build-x64 --config $env:CONFIG -j 2
    - name: test-x86
      working-directory: ${{github.workspace}}
      run: |
        ctest --test-dir build-x86 -j6 --output-on-failure --extra-verbose
    - name: test-x64
      working-directory: ${{github.workspace}}
      run: |
        ctest --test-dir build-x64 -j6 --output-on-failure --extra-verbose
